# Generated by Django 3.0 on 2020-07-01 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(choices=[('BLK', 'Black'), ('WHT', 'White'), ('RED', 'Red'), ('ORNG', 'Orange'), ('YLLW', 'Yellow'), ('GRN', 'Green'), ('BLU', 'Blue'), ('INDG', 'Indigo'), ('VILT', 'Violet')], default='BLK', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('SNKR', 'Sneaker'), ('BT', 'Boot'), ('SDL', 'Sandal'), ('DRS', 'Dress'), ('OTR', 'Other')], default='SNKR', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(max_length=2)),
                ('brand_name', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=20)),
                ('fasten_type', models.CharField(max_length=15)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoe_db_app.ShoeColor')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoe_db_app.Manufacturer')),
                ('shoe_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoe_db_app.ShoeType')),
            ],
        ),
    ]
